export enum ApplicationStatus {
    APPLIED = 'APPLIED',
    AI_PENDING = 'AI_PENDING',
    AI_COMPLETED = 'AI_COMPLETED',
    AUTOMATIC_QUALIFIED = 'AUTOMATIC_QUALIFIED',
    COMPANY_SHORTLISTED = 'COMPANY_SHORTLISTED',
    HIRED = 'HIRED',
    REJECTED = 'REJECTED',
    WITHDRAWN = 'WITHDRAWN'
}