export enum TransactionType {
    DEPOSIT = 'DEPOSIT',
    WITHDRAW = 'WITHDRAW',
    JOB_POST_PAYMENT = 'JOB_POST_PAYMENT',
    SELLER_PAYOUT = 'SELLER_PAYOUT',
    PLATFORM_COMMISSION = 'PLATFORM_COMMISSION',
    REFUND = 'REFUND',
    FREEZE = 'FREEZE'
}