export enum GigOrderStatus {
    ORDER_PLACED = 'ORDER_PLACED',
    QUOTED = 'QUOTED',
    QUOTE_ACCEPTED = 'QUOTE_ACCEPTED',
    QUOTE_REJECTED = 'QUOTE_REJECTED',
    DELIVERED = 'DELIVERED',
    BUYER_ACCEPTED = 'BUYER_ACCEPTED',
    BUYER_REJECTED = 'BUYER_REJECTED',
    BUYER_CANCELLED = 'BUYER_CANCELLED',
    SELLER_CANCELLED = 'SELLER_CANCELLED',
    SELLER_DISPUTED = 'SELLER_DISPUTED',
    PAYMENT_RELEASED = 'PAYMENT_RELEASED',
    REFUNDED = 'REFUNDED'
}

